/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cargo.project;
import com.mysql.cj.protocol.Resultset;
import java.awt.Color;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Employee extends javax.swing.JInternalFrame {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emp_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        emp_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emp_tell = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emp_adress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_save = new javax.swing.JButton();
        e_update = new javax.swing.JButton();
        e_close = new javax.swing.JButton();
        e_delete = new javax.swing.JButton();
        txtsalary = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        emp_gender = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Employee Registration");

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setText("Employee ID:");

        jLabel2.setText("Employee Name:");

        emp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_idActionPerformed(evt);
            }
        });
        emp_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emp_idKeyReleased(evt);
            }
        });

        jLabel3.setText("Employee Tell:");

        emp_tell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emp_tellKeyReleased(evt);
            }
        });

        jLabel4.setText("Employee Address:");

        emp_adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_adressActionPerformed(evt);
            }
        });

        jLabel5.setText("Gender:");

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        btn_save.setBackground(new java.awt.Color(255, 0, 0));
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        e_update.setBackground(new java.awt.Color(255, 0, 0));
        e_update.setText("Update");
        e_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_updateActionPerformed(evt);
            }
        });

        e_close.setBackground(new java.awt.Color(255, 0, 0));
        e_close.setText("Close");
        e_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_closeActionPerformed(evt);
            }
        });

        e_delete.setBackground(new java.awt.Color(255, 0, 0));
        e_delete.setText("Delete");
        e_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_save)
                .addGap(18, 18, 18)
                .addComponent(e_update)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(e_delete)
                .addGap(18, 18, 18)
                .addComponent(e_close)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(e_update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_delete)
                    .addComponent(e_close))
                .addGap(23, 23, 23))
        );

        txtsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsalaryKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsalaryKeyTyped(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Tell", "Address", "Gender", "Salary"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel6.setText("Salary");

        emp_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Male", "Female" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emp_tell, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(emp_id, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(emp_name, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(emp_adress, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(txtsalary, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(emp_gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(emp_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(emp_tell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(emp_adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(emp_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_deleteActionPerformed
        // TODO add your handling code here:
         validation();
          if(emp_id.getText().equals("")){
             JOptionPane.showMessageDialog(this, "Please fill all fields");
        }
        else 
          {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int selectedIndex = jTable2.getSelectedRow();
        try {

            int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
            int dialogResult = JOptionPane.showConfirmDialog (null, "Do you want to Delete the record","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/cargo","root","");
                insert = con1.prepareStatement("delete from employee where emp_id = ?");
               
                 insert.setInt(1,id);
                insert.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Delete");
                emp_id.setText("");
                emp_name.setText("");
                emp_tell.setText("");
                emp_adress.setText("");
             
                txtsalary.setText("");
                emp_id.requestFocus();

                table_update();

            }

        } catch (ClassNotFoundException ex) {

        } catch (SQLException ex) {
        }
        }
    }//GEN-LAST:event_e_deleteActionPerformed

    private void e_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_closeActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_e_closeActionPerformed

    private void e_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_updateActionPerformed
        // TODO add your handling code here:
        validation();
          if(emp_id.getText().equals("") &&  emp_name.getText().equals("")  &&  emp_tell.getText().equals("") && emp_adress.getText().equals("") && txtsalary.getText().equals("")){
        
             JOptionPane.showMessageDialog(this, "Please fill all fields");
        }
        else 
          {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int selectedIndex = jTable2.getSelectedRow();
        try {

            int ids ;
            ids= Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
            
            String name= emp_name.getText();
            String phone= emp_tell.getText();
            String address= emp_adress.getText();
             String gender=emp_gender.getSelectedItem().toString();
            String salary= txtsalary.getText();
             Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/cargo","root","");
            
            insert = con1.prepareStatement("update employee set emp_name= ?,emp_tell= ?,emp_address= ? ,Gender=? , Salary=? where emp_id= ?");

           
            insert.setString(1,name);
            insert.setString(2,phone);
            insert.setString(3,address);
            insert.setString(4,gender);
            insert.setString(5,salary);
            insert.setInt(6,ids);

            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated");

            emp_id.setText("");
            emp_name.setText("");
            emp_tell.setText("");
            emp_adress.setText("");
            emp_gender.remove(this);
            
            txtsalary.setText("");
            emp_id.requestFocus();
            table_update();

        } catch (ClassNotFoundException ex) {

        } catch (SQLException ex) {

        }
          }
    }//GEN-LAST:event_e_updateActionPerformed

    public  void validation(){
    
        
         String salary =txtsalary.getText();
      String id =emp_id.getText();
 
     String Tell=emp_tell.getText();
     
       if(Tell.matches("^[0-9]*$"))
        {
            emp_tell.setBackground(Color.green);   
        } 
        
        else
        {
           
       emp_tell.setBackground(Color.red);
             JOptionPane.showMessageDialog(this, "Phone: only numbers are allowed");
        }
     
       
     
      
        if(id.matches("^[0-9]*$"))
        {
            emp_id.setBackground(Color.green);
           
        } 
        
        else
        {
           
       emp_id.setBackground(Color.red);
             JOptionPane.showMessageDialog(this, "ID: only numbers are allowed");
        }
        
      
       if(salary.matches("^[0-9]*$"))
        {
            txtsalary.setBackground(Color.green);
             
        }
        else
        {
            
       txtsalary.setBackground(Color.red);
             JOptionPane.showMessageDialog(this, " Salary: only numbers are allowed");
        }
        
        
        
        
    }
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        validation();
        
        if(emp_id.getText().equals("") &&  emp_name.getText().equals("")  &&  emp_tell.getText().equals("") && emp_adress.getText().equals("") && txtsalary.getText().equals("")){
        
             JOptionPane.showMessageDialog(this, "Please fill all fields");
        }
        else 
        {
        String id= emp_id.getText();
        String name= emp_name.getText();
        String phone= emp_tell.getText();
        String address= emp_adress.getText();
     String gender=emp_gender.getSelectedItem().toString();
        String salary= txtsalary.getText();

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/cargo","root","");
            insert = con1.prepareStatement("insert into Employee (emp_id ,emp_name,emp_tell, emp_address,Gender,Salary )values(?,?,?,?,?,?)");
            insert.setString(1,id);
            insert.setString(2,name);
            insert.setString(3,phone);
            insert.setString(4,address);
            insert.setString(5,gender);
            insert.setString(6,salary);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
            table_update();
            emp_id.setText("");
            emp_name.setText("");
            emp_tell.setText("");
            emp_adress.setText("");
            emp_gender.remove(this);
            
            txtsalary.setText("");
            emp_id.requestFocus();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Customer_Reg.class.getName()).log(Level.SEVERE, null, ex);

        }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void emp_adressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_adressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_adressActionPerformed

    private void emp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_idActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        
           DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
  int selectedIndex = jTable2.getSelectedRow();
         
 emp_id.setText(model.getValueAt(selectedIndex, 0).toString());
   emp_name.setText(model.getValueAt(selectedIndex, 1).toString());
  emp_tell.setText(model.getValueAt(selectedIndex, 2).toString());
   emp_adress.setText(model.getValueAt(selectedIndex, 3).toString());
    String ge = model.getValueAt(selectedIndex, 4).toString();
     emp_gender.setSelectedItem(ge);
     txtsalary.setText(model.getValueAt(selectedIndex, 5).toString());
    
    }//GEN-LAST:event_jTable2MouseClicked

    private void txtsalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalaryKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtsalaryKeyTyped

    private void txtsalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalaryKeyReleased
        // TODO add your handling code here:
        String salary =txtsalary.getText();
        if(salary.matches("^[0-9]*$"))
        {
            txtsalary.setBackground(Color.green);
            
            
        }
        else
        {
            
       txtsalary.setBackground(Color.red);
                JOptionPane.showMessageDialog(this, " Salary: only numbers are allowed");
        }
    }//GEN-LAST:event_txtsalaryKeyReleased

    private void emp_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_idKeyReleased
        // TODO add your handling code here:
         String salary =emp_id.getText();
        if(salary.matches("^[0-9]*$"))
        {
            emp_id.setBackground(Color.green);
            
            
        }
        else
        {
            
       emp_id.setBackground(Color.red);
    
             JOptionPane.showMessageDialog(this, " ID: only numbers are allowed");
        }
    }//GEN-LAST:event_emp_idKeyReleased

    private void emp_tellKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_tellKeyReleased
        // TODO add your handling code here:
        String Tell =emp_tell.getText();
          if(Tell.matches("^[0-9]*$"))
        {
            emp_tell.setBackground(Color.green);   
        } 
        
        else
        {
           
       emp_tell.setBackground(Color.red);
             JOptionPane.showMessageDialog(this, "Phone: only numbers are allowed");
        }
    }//GEN-LAST:event_emp_tellKeyReleased

     Connection con1;
      PreparedStatement insert;
    
      
           private void table_update() {
        int CC;
        try {
        
            
             Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/cargo","root","");
              
            insert = con1.prepareStatement("SELECT * FROM employee");
            ResultSet Rs = insert.executeQuery();
            
            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) jTable2.getModel();
            DFT.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();
           
                for (int ii = 1; ii <= CC; ii++) {
      
                    v2.add(Rs.getString("emp_id"));
                    v2.add(Rs.getString("emp_name"));
                    v2.add(Rs.getString("emp_tell"));
                    v2.add(Rs.getString("emp_address"));
                    v2.add(Rs.getString("Gender"));
                    v2.add(Rs.getString("Salary"));
                }
                DFT.addRow(v2);
            }
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JButton e_close;
    private javax.swing.JButton e_delete;
    private javax.swing.JButton e_update;
    private javax.swing.JTextField emp_adress;
    private javax.swing.JComboBox<String> emp_gender;
    private javax.swing.JTextField emp_id;
    private javax.swing.JTextField emp_name;
    private javax.swing.JTextField emp_tell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtsalary;
    // End of variables declaration//GEN-END:variables
}
