/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cargo.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;


public class MDIparent extends javax.swing.JFrame {

    /**
     * Creates new form MDIparent
     */
    public MDIparent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        pane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Menu_cust = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        port = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pane.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jMenu1.setText("Customer");

        Menu_cust.setText("Customer Registration");
        Menu_cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_custActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_cust);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Employee ");

        jMenuItem1.setText("Employee Registration");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Port");

        port.setText("Port Registration");
        port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portActionPerformed(evt);
            }
        });
        jMenu3.add(port);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ship");

        jMenuItem2.setText("Ship Registration");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu9.setText("Shipment");

        jMenuItem5.setText("Shipment");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem5);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("Reports");

        jMenuItem4.setText("All report");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem4);

        jMenuItem6.setText("Employee Report");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem6);

        jMenuItem7.setText("Customer Report");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem7);

        jMenuItem8.setText("jMenuItem8");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem8);

        jMenuBar1.add(jMenu10);

        jMenu6.setText("Cargo");

        jMenuItem3.setText("Cargo Registration");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_custActionPerformed
        // TODO add your handling code here:
        Customer_Reg cr = new Customer_Reg();
        cr.setVisible(true);
        cr.moveToFront();
  
        cr.setLocation(50,50);
       pane.add(cr);  
    }//GEN-LAST:event_Menu_custActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
            Employee  em =new Employee();
       
        em.setVisible(true);
        em.moveToFront();
         em.setLocation(50,50);
       pane.add(em);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Ship  em =new Ship();
       
        em.setVisible(true);
        em.moveToFront();
         em.setLocation(50,50);
       pane.add(em);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Cargo  em =new Cargo();
       
        em.setVisible(true);
        em.moveToFront();
         em.setLocation(50,50);
       pane.add(em);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portActionPerformed
        // TODO add your handling code here:
        Port  em =new Port();
       
        em.setVisible(true);
        em.moveToFront();
         em.setLocation(50,50);
       pane.add(em);
    }//GEN-LAST:event_portActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
          Shipments  em =new Shipments();
       
        em.setVisible(true);
        em.moveToFront();
         em.setLocation(50,50);
       pane.add(em);
    }//GEN-LAST:event_jMenuItem5ActionPerformed
  
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
                Connection con1;
      PreparedStatement insert;
         try {
               
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/cargo","root","");
          
            String Report = "C:\\Users\\HP\\Desktop\\java swing pro\\java swing pro\\CargoProject\\Cargo Project\\src\\cargo\\project\\AllReport.jrxml";
            JasperDesign jdesign= JRXmlLoader.load(Report);
          
          String q= "SELECT\n" +
"     customers.`cust_id` AS customers_cust_id,\n" +
"     customers.`cust_name` AS customers_cust_name,\n" +
"     customers.`cust_tell` AS customers_cust_tell,\n" +
"     customers.`cust_address` AS customers_cust_address,\n" +
"     customers.`Gender` AS customers_Gender,\n" +
"     cargo.`cargo_name` AS cargo_cargo_name,\n" +
"     cargo.`cargo_item` AS cargo_cargo_item,\n" +
"     cargo.`nkg` AS cargo_nkg,\n" +
"     cargo.`Payment` AS cargo_Payment,\n" +
"     port.`port_name` AS port_port_name,\n" +
"     port.`country` AS port_country,\n" +
"     port.`region` AS port_region,\n" +
"     port.`district` AS port_district,\n" +
"     ship.`ship_name` AS ship_ship_name,\n" +
"     ship.`contact` AS ship_contact,\n" +
"     shipment.`port_Source` AS shipment_port_Source,\n" +
"     shipment.`port_Distination` AS shipment_port_Distination\n" +
"FROM\n" +
"     `cargo` cargo INNER JOIN `shipment` shipment ON cargo.`cargo_id` = shipment.`cargoID`\n" +
"     INNER JOIN `customers` customers ON shipment.`custID` = customers.`cust_id`\n" +
"     INNER JOIN `port` port ON shipment.`portID` = port.`port_id`\n" +
"     INNER JOIN `ship` ship ON shipment.`shipID` = ship.`ship_id`";
          JRDesignQuery updateQuery =new JRDesignQuery();
          updateQuery.setText(q);
          
                  
        
JasperReport JASP = JasperCompileManager.compileReport(jdesign);
JasperPrint JPrint = JasperFillManager.fillReport(JASP, null, con1);
JasperViewer.viewReport(JPrint);
   
              }
         catch (ClassNotFoundException | SQLException | JRException ex) { JOptionPane.showMessageDialog(null, ex); }

     
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        
           Connection con1;
      PreparedStatement insert;
         try {
               
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/cargo","root","");
          
            String Report = "C:\\Users\\HP\\Desktop\\java swing pro\\java swing pro\\CargoProject\\Cargo Project\\src\\cargo\\project\\report1.jrxml";
         
            JasperDesign jdesign= JRXmlLoader.load(Report);
          
          String q= "SELECT\n" +
"     employee.`emp_id` AS employee_emp_id,\n" +
"     employee.`emp_name` AS employee_emp_name,\n" +
"     employee.`emp_tell` AS employee_emp_tell,\n" +
"     employee.`emp_address` AS employee_emp_address,\n" +
"     employee.`Gender` AS employee_Gender,\n" +
"     employee.`Salary` AS employee_Salary\n" +
"FROM\n" +
"     `employee` employee";
          JRDesignQuery updateQuery =new JRDesignQuery();
          updateQuery.setText(q);
          
                  
        
JasperReport JASP = JasperCompileManager.compileReport(jdesign);
JasperPrint JPrint = JasperFillManager.fillReport(JASP, null, con1);
JasperViewer.viewReport(JPrint);
   
              }
         catch (ClassNotFoundException | SQLException | JRException ex) { JOptionPane.showMessageDialog(null, ex); }

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Connection con1;
    
         try {
               
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/cargo","root","");
          String Report = "C:\\Users\\HP\\Desktop\\java swing pro\\java swing pro\\CargoProject\\Cargo Project\\src\\cargo\\project\\cust.jrxml"; 
     
          JasperDesign jdesign= JRXmlLoader.load(Report);
          
          String q= "SELECT\n customers.`cust_id` AS customers_cust_id,\n customers.`cust_name` AS customers_cust_name,\n" +
"     customers.`cust_tell` AS customers_cust_tell,\n" +
"     customers.`cust_address` AS customers_cust_address,\n" +
"     customers.`Gender` AS customers_Gender,\n" +
"     cargo.`cargo_name` AS cargo_cargo_name,\n" +
"     cargo.`cargo_item` AS cargo_cargo_item,\n" +
"     cargo.`nkg` AS cargo_nkg,\n" +
"     cargo.`Payment` AS cargo_Payment,\n" +
"     port.`port_name` AS port_port_name,\n" +
"     port.`country` AS port_country,\n" +
"     port.`region` AS port_region,\n" +
"     port.`district` AS port_district,\n" +
"     ship.`ship_name` AS ship_ship_name,\n" +
"     ship.`contact` AS ship_contact,\n" +
"     shipment.`port_Source` AS shipment_port_Source,\n" +
"     shipment.`port_Distination` AS shipment_port_Distination\n" +
"FROM\n" +
"     `cargo` cargo INNER JOIN `shipment` shipment ON cargo.`cargo_id` = shipment.`cargoID`\n" +
"     INNER JOIN `customers` customers ON shipment.`custID` = customers.`cust_id`\n" +
"     INNER JOIN `port` port ON shipment.`portID` = port.`port_id`\n" +
"     INNER JOIN `ship` ship ON shipment.`shipID` = ship.`ship_id`" ;
          JRDesignQuery updateQuery =new JRDesignQuery();
          updateQuery.setText(q);
          
JasperReport JASP = JasperCompileManager.compileReport(jdesign);
JasperPrint JPrint = JasperFillManager.fillReport(JASP, null, con1);
JasperViewer.viewReport(JPrint);
   
              }
         catch (ClassNotFoundException | SQLException | JRException ex) { JOptionPane.showMessageDialog(null, ex); }

         
  
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
          Shipments  em =new Shipments();
       
        em.setVisible(true);
        em.moveToFront();
         em.setLocation(50,50);
       pane.add(em);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIparent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIparent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIparent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIparent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIparent().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_cust;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JDesktopPane pane;
    private javax.swing.JMenuItem port;
    // End of variables declaration//GEN-END:variables
}


