/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cargo.project;
import java.awt.Color;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Port extends javax.swing.JInternalFrame {

    /**
     * Creates new form Port
     */
    public Port() {
        initComponents();
         table_update();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        port_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        port_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        con = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        region = new javax.swing.JComboBox<>();
        state = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        p_save = new javax.swing.JButton();
        p_update = new javax.swing.JButton();
        p_delete = new javax.swing.JButton();
        p_close = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 255, 255));
        setClosable(true);
        setTitle("Port Registration");

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setText("Port_ID");

        port_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                port_idKeyReleased(evt);
            }
        });

        jLabel2.setText("Port_Name:");

        jLabel3.setText("Country");

        jLabel4.setText("Region: ");

        jLabel5.setText("District");

        region.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "please select one", "Awdal", "Baay", "Bakool", "Banaadir", "Bari", "Galgaduud", "Gedo", "Hiiraan", "J/dhaxe", "J/Hoose", "Mudug", "Nugaal", "Sanaag", "Sh/Dhaxe", "Sh/Hoose", "Sool", "Togdheer", "W/Galbeed", " " }));
        region.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regionMouseClicked(evt);
            }
        });
        region.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(37, 37, 37)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(port_name, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(con, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(port_id, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(region, 0, 183, Short.MAX_VALUE)
                            .addComponent(state, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(port_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(port_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 204));

        p_save.setBackground(new java.awt.Color(255, 0, 0));
        p_save.setText("Save");
        p_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_saveActionPerformed(evt);
            }
        });

        p_update.setBackground(new java.awt.Color(255, 0, 0));
        p_update.setText("Update");
        p_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_updateActionPerformed(evt);
            }
        });

        p_delete.setBackground(new java.awt.Color(255, 0, 0));
        p_delete.setText("Delete");
        p_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_deleteActionPerformed(evt);
            }
        });

        p_close.setBackground(new java.awt.Color(255, 0, 0));
        p_close.setText("Close");
        p_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(p_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p_close, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p_save, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(p_update))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_save)
                    .addComponent(p_update))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_close)
                    .addComponent(p_delete))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Port Name", "Country", "Region", "District"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       Connection con1;
      PreparedStatement insert;
       private void table_update() {
        int CC;
        try {
            
           Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/cargo","root","");
            insert = con1.prepareStatement("SELECT * FROM PORT");
            ResultSet Rs = insert.executeQuery();
            
            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) jTable2.getModel();
            DFT.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();
                
                for (int ii = 1; ii <= CC; ii++) {
                    
                    v2.add(Rs.getString("PORT_ID"));
                    v2.add(Rs.getString("PORT_NAME"));
                    v2.add(Rs.getString("COUNTRY"));
                    v2.add(Rs.getString("REGION"));
                    v2.add(Rs.getString("DISTRICT"));
      
                }
                DFT.addRow(v2);
            }
        } catch (Exception e) {
        }
    }
       
    private void p_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_closeActionPerformed
        // TODO add your handling code here:
         dispose();
         
    }//GEN-LAST:event_p_closeActionPerformed

    private void p_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_saveActionPerformed
        // TODO add your handling code here:
        validation();
         if(port_id.getText().equals("") &&  port_name.getText().equals("")  &&  con.getText().equals("") ){
        
             JOptionPane.showMessageDialog(this, "Please fill all fields");
        }
        else 
        {
          String id= port_id.getText();
       String name= port_name.getText();
        String coun= con.getText();
        String reg =region.getSelectedItem().toString();
        
         String dis= state.getSelectedItem().toString();
        try {
           
             Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/cargo","root","");
            
            insert = con1.prepareStatement("insert into PORT values(?,?,?,?,?)");
            insert.setString(1,id);
            insert.setString(2,name);
            insert.setString(3,coun);
             insert.setString(4,reg);
            insert.setString(5,dis);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");  
               table_update();
            port_id.setText("");
            port_name.setText("");
            con.setText("");
           
          
              table_update();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customer_Reg.class.getName()).log(Level.SEVERE, null, ex);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Port.class.getName()).log(Level.SEVERE, null, ex);
            
        }    
        }
         
        
        
    }//GEN-LAST:event_p_saveActionPerformed

    private void p_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_updateActionPerformed
        // TODO add your handling code here:
        
        validation();
         if(port_id.getText().equals("") &&  port_name.getText().equals("")  &&  con.getText().equals("") ){
        
             JOptionPane.showMessageDialog(this, "Please fill all fields");
        }
        else 
        {
          String id= port_id.getText();
       String name= port_name.getText();
        String coun= con.getText();
        String reg =region.getSelectedItem().toString();
         String dis= state.getSelectedItem().toString();
          DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            int selectedIndex = jTable2.getSelectedRow();
        try {
            
             int ids = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
             Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/cargo","root","");
          insert = con1.prepareStatement("update PORT set  PORT_NAME= ?, COUNTRY= ?,REGION= ? ,DISTRICT=?  where PORT_ID= ?");

            insert.setString(1,name);
            insert.setString(2,coun);
             insert.setString(3,reg);
            insert.setString(4,dis);
             insert.setInt(5,ids);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated");  
             table_update();
            port_id.setText("");
            port_name.setText("");
            con.setText("");
            region.removeAllItems();
            state.removeAllItems();
           table_update();
           
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Port.class.getName()).log(Level.SEVERE, null, ex);
            
            
        }    
        }
         
        
        
    }//GEN-LAST:event_p_updateActionPerformed

    private void regionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regionMouseClicked
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_regionMouseClicked

    private void regionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionActionPerformed
        // TODO add your handling code here:
        
     
        if(region.getSelectedItem().equals("Awdal"))
        {
            state.removeAllItems();
            state.setSelectedItem(null);
        state.addItem("Boorama");
         state.addItem("Baki");
          state.addItem("Saylac");
          
        
        }
        
        else if(region.getSelectedItem().equals("Baay"))
        {
            state.removeAllItems();
             state.setSelectedItem(null);
        state.addItem("Baydhabo");
         state.addItem("Baki");
          state.addItem("Saylac");
          
        
        }
        else if(region.getSelectedItem().equals("Bakool"))
        {
            state.removeAllItems();
             state.setSelectedItem(null);
        state.addItem("Xudur");
         state.addItem("Ceelbarde");
          state.addItem("Tiyeeglow");
          
        }
        
        else if(region.getSelectedItem().equals("Banaadir"))
        {
            state.removeAllItems();
            
          state.setSelectedItem(null);;   
            
            state.addItem("Boondheere");
            state.addItem("Cabdicasiis");
        state.addItem("Xamarjajab");
         state.addItem("xamarweyne");
        
          state.addItem("Shibis");
          state.addItem("shingaani");
         state.addItem("Dharkeenleey");
          state.addItem("Deyliine");
          state.addItem("Hodan");
           state.addItem("Howlwadaag");
          state.addItem("Heliwaa");
          state.addItem("Waaberi");
           state.addItem("Wadajir");
          state.addItem("Warta Nabadda ");
         state.addItem("Kaaraan");
         state.addItem("Kaxda");
         state.addItem("Yaaqshid");
          state.addItem("Heliwaa");
          
          
        }
        else if(region.getSelectedItem().equals("Galgaduud"))
        {
            state.removeAllItems();
          state.setSelectedItem(null);
        state.addItem("Samareeb");
         state.addItem("Ceeldheer");
          state.addItem("Caabudwaaq");
           state.addItem("Ceelbuur");
          state.addItem("Cadaado");
           state.addItem("Guriceel");
        
            
        
        }
         else if(region.getSelectedItem().equals("Bari"))
        {
            state.removeAllItems();
          state.setSelectedItem(null);
        state.addItem("Bosaaso");
         state.addItem("Qardho");
          state.addItem("Qandhala");
           state.addItem("Caluula");
          state.addItem("Ishushuban");
          
        
     
        }
        else if(region.getSelectedItem().equals("Gedo"))
        {state.removeAllItems();
        
          state.setSelectedItem(null);
        state.addItem("Beled Xaawo");
            state.addItem("Burdhubo");
            state.addItem("Bardhere");
            state.addItem("Doolow");
           state.addItem("Ceelwaaq");
         state.addItem("Garbaharey"); 
           state.addItem("Luuq");
          
     
     
        }
        else if(region.getSelectedItem().equals("Hiiraan"))
        {
            state.removeAllItems();
          state.setSelectedItem(null);
        state.addItem("Beledweyne");
         state.addItem("Bulo barde");
          state.addItem("Jalalaqsi");
           state.addItem("Maxaas");
          state.addItem("Matabaan");
        }
        else if(region.getSelectedItem().equals("J/dhaxe"))
        {
            state.removeAllItems();
          state.setSelectedItem(null);
        state.addItem("Bu'aale");
         state.addItem("Jilib");
          state.addItem("Saakow");
         
        }
        else if(region.getSelectedItem().equals("J/Hoose"))
        {
            state.removeAllItems();
            state.setSelectedItem(null);

        state.addItem("Kismaayo");
         state.addItem("Afmadow");
          state.addItem("Jamaame");
           state.addItem("Buulo Xaaji");
         
        }
            else if(region.getSelectedItem().equals("Mudug"))
        {
            state.removeAllItems();
            state.setSelectedItem(null);

        state.addItem("Kalgacyo");
         state.addItem("Galdogob");
          state.addItem("Hobyo");
           state.addItem("Xaradheer");
           state.addItem("Bandiiradley");
         
        }
                else if(region.getSelectedItem().equals("Nugaal"))
        {
            state.removeAllItems();
            
state.setSelectedItem(null);
        state.addItem("Garoowe");
         state.addItem("Burtinle");
          state.addItem("Ely");
          
         
        }
                else if(region.getSelectedItem().equals("Sanaag"))
        {
            state.removeAllItems();
            state.setSelectedItem(null);

        state.addItem("Ceerigaabo");
         state.addItem("Badhan");
          state.addItem("Dhahar");
           state.addItem("Las Qoray");
         
        }
             else if(region.getSelectedItem().equals("Sh/Dhaxe"))
        {
            state.removeAllItems();
            state.setSelectedItem(null);

        state.addItem("Jowhar");
         state.addItem("Mahaday");
          state.addItem("Balcad");
          state.addItem("Cadale");
           
        }
                     else if(region.getSelectedItem().equals("Sh/Hoose"))
        {
            state.removeAllItems();
            state.setSelectedItem(null);

        state.addItem("Marka");
         state.addItem("Baraawe");
          state.addItem("Afgooye");
          state.addItem("Wanlaweyn");
           
        }
        
        
                else if(region.getSelectedItem().equals("Sool"))
        {
            state.removeAllItems();
            state.setSelectedItem(null);

        state.addItem("Laascaanood");
         state.addItem("Taleex");
          state.addItem("Caynaba");
          state.addItem("Wanlaweyn");
           
        }


   else if(region.getSelectedItem().equals("Togdheer"))
        {
            state.removeAllItems();
            state.setSelectedItem(null);

        state.addItem("Burco");
         state.addItem("Oodweyne");
          state.addItem("Buhoodle");
         
           
        }
         else if(region.getSelectedItem().equals("W/Galbeed"))
        {
            state.removeAllItems();
        state.setSelectedItem(null);

        
        state.addItem("Hargeysa");
         state.addItem("Berbera");
          state.addItem("Gabiley");
         
           
        }





    }//GEN-LAST:event_regionActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
             DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
  int selectedIndex = jTable2.getSelectedRow();
         
          port_id.setText(model.getValueAt(selectedIndex, 0).toString());
        port_name.setText(model.getValueAt(selectedIndex, 1).toString());
        con.setText(model.getValueAt(selectedIndex, 2).toString());
      String cm=model.getValueAt(selectedIndex, 3).toString();
       String s=model.getValueAt(selectedIndex, 4).toString();
      region.setSelectedItem(cm);
      state.setSelectedItem(s);
  
        
    }//GEN-LAST:event_jTable2MouseClicked
    public  void validation(){
       
      String id =port_id.getText();
 
        if(id.matches("^[0-9]*$"))
        {
            port_id.setBackground(Color.green);
           
        } 
        
        else
        {
           
       port_id.setBackground(Color.red);
             JOptionPane.showMessageDialog(this, "ID: only numbers are allowed");
        }
        
    }
    private void p_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_deleteActionPerformed
        // TODO add your handling code here:
        validation();
         DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
          int selectedIndex = jTable2.getSelectedRow();
            try {   
                
            int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
            int dialogResult = JOptionPane.showConfirmDialog (null, "Do you want to Delete the record","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){

           Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/cargo","root","");  
            insert = con1.prepareStatement("delete from PORT where PORT_ID = ?");
            insert.setInt(1,id);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Delete");
             port_id.setText("");
            port_name.setText("");
            con.setText("");
            region.removeAllItems();
            state.removeAllItems();
            table_update();
           
           }

        } catch (ClassNotFoundException ex) {
        
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_p_deleteActionPerformed

    private void port_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_port_idKeyReleased
        // TODO add your handling code here:
         String id =port_id.getText();
 
        if(id.matches("^[0-9]*$"))
        {
            port_id.setBackground(Color.green);
           
        } 
        
        else
        {
           
       port_id.setBackground(Color.red);
             JOptionPane.showMessageDialog(this, "ID: only numbers are allowed");
        }
    }//GEN-LAST:event_port_idKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField con;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton p_close;
    private javax.swing.JButton p_delete;
    private javax.swing.JButton p_save;
    private javax.swing.JButton p_update;
    private javax.swing.JTextField port_id;
    private javax.swing.JTextField port_name;
    private javax.swing.JComboBox<String> region;
    private javax.swing.JComboBox<String> state;
    // End of variables declaration//GEN-END:variables
}
