/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cargo.project;



import java.awt.Color;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class Ship extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ship
     */
    public Ship() {
        initComponents();
        
             table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtship_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtship_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        save_s = new javax.swing.JButton();
        delete_s = new javax.swing.JButton();
        update_s = new javax.swing.JButton();
        close_s = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 255, 255));
        setClosable(true);
        setTitle("Ship Registration");

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setText("Ship_ID:");

        txtship_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtship_idActionPerformed(evt);
            }
        });
        txtship_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtship_idKeyReleased(evt);
            }
        });

        jLabel2.setText("Ship_Name:");

        txtship_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtship_nameActionPerformed(evt);
            }
        });

        jLabel3.setText("Contact:");

        txtcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontactActionPerformed(evt);
            }
        });
        txtcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcontactKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcontact, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(txtship_id, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(txtship_name))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtship_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtship_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        save_s.setBackground(new java.awt.Color(255, 0, 0));
        save_s.setText("Save");
        save_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_sActionPerformed(evt);
            }
        });

        delete_s.setBackground(new java.awt.Color(255, 0, 0));
        delete_s.setText("Delete");
        delete_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_sActionPerformed(evt);
            }
        });

        update_s.setBackground(new java.awt.Color(255, 0, 0));
        update_s.setText("Update");
        update_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_sActionPerformed(evt);
            }
        });

        close_s.setBackground(new java.awt.Color(255, 0, 0));
        close_s.setText("Close  ");
        close_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_sActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delete_s, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(save_s, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_s)
                    .addComponent(close_s))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_s)
                    .addComponent(update_s))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close_s)
                    .addComponent(delete_s))
                .addGap(43, 43, 43))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Contact"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 Connection con1;
      PreparedStatement insert;
      
      
       private void table_update() {
        int CC;
        try {
            
             Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/cargo","root","");
              
            insert = con1.prepareStatement("SELECT * FROM ship");
            ResultSet Rs = insert.executeQuery();
            
            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
            DFT.setRowCount(0);
            while (Rs.next()) {
                Vector v2 = new Vector();
                for (int ii = 1; ii <= CC; ii++) {
      
                    v2.add(Rs.getString("ship_id"));
                    v2.add(Rs.getString("ship_name"));
                    v2.add(Rs.getString("contact"));
                  
                }
                DFT.addRow(v2);
            }
        } catch (Exception e) {
        }
    }
       
    
    private void txtship_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtship_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtship_idActionPerformed

    private void txtship_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtship_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtship_nameActionPerformed

    private void txtcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactActionPerformed

    private void delete_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_sActionPerformed
        // TODO add your handling code here:
        validation();
                  DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
          int selectedIndex = jTable1.getSelectedRow();
            try {   
                
            int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
            int dialogResult = JOptionPane.showConfirmDialog (null, "Do you want to Delete the record","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){

            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/cargo","root","");
            insert = con1.prepareStatement("delete from ship where ship_id = ?");
        
            insert.setInt(1,id);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Delete");
            txtship_id.setText("");
            txtship_name.setText("");
            txtcontact.setText("");

            table_update();
           
           }

        } catch (ClassNotFoundException | SQLException ex) {
        
        }
        
        
    }//GEN-LAST:event_delete_sActionPerformed

    private void save_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_sActionPerformed
        // TODO add your handling code here:
        validation();
        if(txtship_id.getText().equals("") && txtship_name.getText().equals("") &&  txtcontact.getText().equals("")){
        
             JOptionPane.showMessageDialog(this, " Please fill all fields");
        }
        else 
        {
         String id= txtship_id.getText();
       String name= txtship_name.getText();
        String cont= txtcontact.getText();
      
         
     
        try {
           
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/cargo","root","");
            insert = con1.prepareStatement("insert into ship (ship_id ,ship_name,contact)values(?,?,?)");
            insert.setString(1,id);
            insert.setString(2,name);
            insert.setString(3,cont);
             
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");  
            
            txtship_id.setText("");
            txtship_name.setText("");
            txtcontact.setText("");

             table_update();
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customer_Reg.class.getName()).log(Level.SEVERE, null, ex);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Customer_Reg.class.getName()).log(Level.SEVERE, null, ex);
            
        }    
         
        }
        
    }//GEN-LAST:event_save_sActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
  int selectedIndex = jTable1.getSelectedRow();
      
 txtship_id.setText(model.getValueAt(selectedIndex, 0).toString());
txtship_name.setText(model.getValueAt(selectedIndex, 1).toString());
txtcontact.setText(model.getValueAt(selectedIndex, 2).toString());

        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void close_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_sActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_close_sActionPerformed

    private void update_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_sActionPerformed
        // TODO add your handling code here:
        validation();
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int selectedIndex = jTable1.getSelectedRow();
            try {   
                
            int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
            String ii =txtship_id.getText();
            String  name=txtship_name.getText();
            String cons =txtcontact.getText();
  
           Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/cargo","root","");
            insert = con1.prepareStatement("update ship set ship_name= ?,contact= ? where ship_id= ?");
            
            insert.setString(1,name);
            insert.setString(2,cons);
            insert.setInt(3,id);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated");
            txtship_id.setText("");
            txtship_name.setText("");
            txtcontact.setText("");
            table_update();
           
            
        } catch (ClassNotFoundException ex) {
           
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_update_sActionPerformed

      public  void validation(){
       
      String id =txtship_id.getText();
 String con=txtcontact.getText();
        if(id.matches("^[0-9]*$"))
        {
            txtship_id.setBackground(Color.green);
           
        } 
        
        else
        {
           
       txtship_id.setBackground(Color.red);
       
             JOptionPane.showMessageDialog(this, "ID: only numbers are allowed");
        }
        
           if(con.matches("^[0-9]*$"))
        {
            txtcontact.setBackground(Color.green);
           
        } 
        
        else
        {
           
       txtcontact.setBackground(Color.red);
             JOptionPane.showMessageDialog(this, "Contact: only numbers are allowed");
        } 
    }
    private void txtship_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtship_idKeyReleased
        // TODO add your handling code here:
        String id =txtship_id.getText();

        if(id.matches("^[0-9]*$"))
        {
            txtship_id.setBackground(Color.green);
           
        } 
        
        else
        {
           
       txtship_id.setBackground(Color.red);
       
             JOptionPane.showMessageDialog(this, "ID: only numbers are allowed");
        }
        
        
    }//GEN-LAST:event_txtship_idKeyReleased

    private void txtcontactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontactKeyReleased
        // TODO add your handling code here:
        String con=txtcontact.getText();
            if(con.matches("^[0-9]*$"))
        {
            txtcontact.setBackground(Color.green);
           
        } 
        
        else
        {
           
       txtcontact.setBackground(Color.red);
             JOptionPane.showMessageDialog(this, "Contact: only numbers are allowed");
        }
    }//GEN-LAST:event_txtcontactKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_s;
    private javax.swing.JButton delete_s;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton save_s;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtship_id;
    private javax.swing.JTextField txtship_name;
    private javax.swing.JButton update_s;
    // End of variables declaration//GEN-END:variables
}
